platform_testing: Remove host_tests to fix custom out dir builds
Remove host_tests section that caused Soong path validation errors
when building with custom output directories.
The individual test modules are still built independently.

fixes:
error: platform_testing/Android.bp:5:1: module "platform_tests" variant "android_common": Path is outside directory: $customoutdir/rom/host/linux-x86/bin/perfetto_trace_processor_shell
error: platform_testing/Android.bp:5:1: module "platform_tests" variant "android_common": Path is outside directory: $customoutdir/rom/host/linux-x86/bin/root-canal